name       : spectacle
version    : 18.08.0
release    : 14
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.0/src/spectacle-18.08.0.tar.xz : 79ea0e535e168ff42ee63a6e784780649cd1ea4749ff677f68542651d4c782bd
license    :
    - GFDL-1.3
    - GPL-2.0
    - LGPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KDE Screenshot Utility
description: |
    Spectacle is screenshot taking utility for the KDE desktop. Spectacle can also be used in non-KDE X11 desktop environments.
builddeps  :
    - pkgconfig(kscreen2)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcb-util)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kdeclarative-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - knotifications-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - libkipi-devel
    - purpose-devel
rundeps    :
    - digikam-kipi-plugins
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
