name       : spectacle
version    : 17.08.3
release    : 4
source     :
    - https://cdn.download.kde.org/stable/applications/17.08.3/src/spectacle-17.08.3.tar.xz : a6fe666f8cfe5c064354fd7f025da88f03da25d49bd7390eb38604341ad6e0a3
license    :
    - GFDL-1.3
    - GPL-2.0
    - LGPL-2.0
    - LGPL-2.1
component  : desktop.kde
summary    : KDE Screenshot Utility
description: |
    Spectacle is screenshot taking utility for the KDE desktop. Spectacle can also be used in non-KDE X11 desktop environments.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(kscreen2)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcb-util)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kdeclarative-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - knotifications-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - libkipi-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
