name       : spectacle
version    : 19.04.3
release    : 26
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.3/src/spectacle-19.04.3.tar.xz : bbf2c17298608dc69139f1f0a07de05b724d83cf57e8fe085a376723d83d15d1
license    :
    - GFDL-1.3-or-later
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : desktop.kde.core
optimize   : lto
summary    : KDE Screenshot Utility
description: |
    Spectacle is screenshot taking utility for the KDE desktop. Spectacle can also be used in non-KDE X11 desktop environments.
builddeps  :
    - pkgconfig(kscreen2)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcb-util)
    - extra-cmake-modules
    - kdeclarative-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - knotifications-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - libkipi-devel
    - purpose-devel
rundeps    :
    - kipi-plugins
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
