name       : spectacle
version    : 17.08.1
release    : 2
source     :
    - https://download.kde.org/stable/applications/17.08.1/src/spectacle-17.08.1.tar.xz : 294b92f528a147993ba735dcfaebe1ec68fecaf605d19900a160fe244c0ca01f
license    :
    - GFDL-1.3
    - GPL-2.0
    - LGPL-2.0
    - LGPL-2.1
component  : desktop.kde
summary    : KDE Screenshot Utility
description: |
    Spectacle is screenshot taking utility for the KDE desktop. Spectacle can also be used in non-KDE X11 desktop environments.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(kscreen2)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcb-util)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kdeclarative-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - knotifications-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - kxmlgui-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
