name       : spectacle
version    : 22.04.2
release    : 65
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.2/src/spectacle-22.04.2.tar.xz : 1e84a1781cacfc96e7990accbe23a88ea5f8c3597cc283a05907a3273fabf73c
homepage   : https://kde.org/applications/utilities/org.kde.spectacle
license    :
    - GFDL-1.3-or-later
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : desktop.kde.core
summary    : KDE Screenshot Utility
description: |
    Spectacle is screenshot taking utility for the KDE desktop. Spectacle can also be used in non-KDE X11 desktop environments.
optimize   : lto
builddeps  :
    - pkgconfig(kscreen2)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcb-util)
    - kdeclarative-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - kguiaddons-devel
    - kimageannotator-devel
    - kcolorpicker-devel
    - kio-devel
    - knewstuff-devel
    - knotifications-devel
    - kwayland-devel
    - purpose-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
