name       : spectacle
version    : 17.08.2
release    : 3
source     :
    - https://download.kde.org/stable/applications/17.08.2/src/spectacle-17.08.2.tar.xz : 1276f3f7af3130b44f489ec64184ef82966fd04e249b49f7036027a347a368f3
license    :
    - GFDL-1.3
    - GPL-2.0
    - LGPL-2.0
    - LGPL-2.1
component  : desktop.kde
summary    : KDE Screenshot Utility
description: |
    Spectacle is screenshot taking utility for the KDE desktop. Spectacle can also be used in non-KDE X11 desktop environments.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(kscreen2)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcb-util)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kdeclarative-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - knotifications-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - kxmlgui-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
