name       : spectacle
version    : 19.12.1
release    : 33
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.1/src/spectacle-19.12.1.tar.xz : 140f388c531043eeefff8d639eb468d1ed33397925021c6809c0c8a799bb25c9
homepage   : https://kde.org/applications/utilities/org.kde.spectacle
license    :
    - GFDL-1.3-or-later
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : desktop.kde.core
optimize   : lto
summary    : KDE Screenshot Utility
description: |
    Spectacle is screenshot taking utility for the KDE desktop. Spectacle can also be used in non-KDE X11 desktop environments.
builddeps  :
    - pkgconfig(kscreen2)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcb-util)
    - extra-cmake-modules
    - kdeclarative-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - knotifications-devel
    - kwayland-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - libkipi-devel
    - purpose-devel
rundeps    :
    - kipi-plugins
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
