name       : spectacle
version    : 18.04.3
release    : 13
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.3/src/spectacle-18.04.3.tar.xz : 4b5cc083a51686fda2ad408915b577e13f34601fd4f186bd3ed46be05ac15be2
license    :
    - GFDL-1.3
    - GPL-2.0
    - LGPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KDE Screenshot Utility
description: |
    Spectacle is screenshot taking utility for the KDE desktop. Spectacle can also be used in non-KDE X11 desktop environments.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(kscreen2)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcb-util)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kdeclarative-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - knotifications-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - libkipi-devel
    - purpose-devel
rundeps    :
    - digikam-kipi-plugins
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
