name       : spectacle
version    : 20.04.0
release    : 37
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.0/src/spectacle-20.04.0.tar.xz : 845beb8c6d11bfb2c37959f209ab8aeb8ed255c64b644711131cbb74967df69f
homepage   : https://kde.org/applications/utilities/org.kde.spectacle
license    :
    - GFDL-1.3-or-later
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : desktop.kde.core
optimize   : lto
summary    : KDE Screenshot Utility
description: |
    Spectacle is screenshot taking utility for the KDE desktop. Spectacle can also be used in non-KDE X11 desktop environments.
builddeps  :
    - pkgconfig(kscreen2)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcb-util)
    - extra-cmake-modules
    - kdeclarative-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - knotifications-devel
    - kwayland-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - libkipi-devel
    - purpose-devel
rundeps    :
    - kipi-plugins
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
