name       : spectacle
version    : 17.12.2
release    : 7
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.2/src/spectacle-17.12.2.tar.xz : 723f9243813e14ac78f3f0a4c5e0aec48679a81d28c86bc7bb1f6732dbb51062
license    :
    - GFDL-1.3
    - GPL-2.0
    - LGPL-2.0
    - LGPL-2.1
component  : desktop.kde
optimize   : lto
summary    : KDE Screenshot Utility
description: |
    Spectacle is screenshot taking utility for the KDE desktop. Spectacle can also be used in non-KDE X11 desktop environments.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(kscreen2)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcb-util)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kdeclarative-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - knotifications-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - libkipi-devel
rundeps    :
    - digikam-kipi-plugins
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
